/**
 * Post Routes
 * Handles all blog post related endpoints
 * @route /api/posts
 */

import express from 'express';
import Post from '../models/Post.js';
import { protect } from '../middleware/authMiddleware.js';

const router = express.Router();

/**
 * Get all posts
 * @route GET /api/posts
 * @access Public
 * @returns {Array} List of all posts sorted by creation date (newest first)
 */
router.get('/', async (req, res) => {
  try {
    const posts = await Post.find()
      .sort({ createdAt: -1 })
      .populate('author', 'username avatar');
    res.json(posts);
  } catch (err) {
    console.error('[getAllPosts]', err);
    res.status(500).json({ message: err.message || 'Failed to fetch posts' });
  }
});


/**
 * Create a new post
 * @route POST /api/posts
 * @access Private
 * @requires Authentication
 */
router.post('/', protect, async (req, res) => {
  try {
    const { title, content, tags } = req.body;

    if (!title || !content) {
      return res.status(400).json({ message: 'Title and content are required' });
    }

    // Slug will be auto-generated by Post model pre-save hook
    const post = new Post({
      title,
      content,
      tags: tags || [],
      author: req.user._id,
    });

    const createdPost = await post.save();
    res.status(201).json(createdPost);
  } catch (err) {
    console.error('[createPost]', err);
    res.status(400).json({ message: err.message || 'Failed to create post' });
  }
});

/**
 * Get a single post by slug
 * @route GET /api/posts/slug/:slug
 * @access Public
 * @param {string} slug - Post slug (URL-friendly identifier)
 */
router.get('/slug/:slug', async (req, res) => {
  try {
    const post = await Post.findOne({ slug: req.params.slug })
      .populate('author', 'username avatar bio');
    
    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }
    
    res.json(post);
  } catch (err) {
    console.error('[getPostBySlug]', err);
    res.status(500).json({ message: err.message || 'Failed to fetch post' });
  }
});


/**
 * Update a post by slug
 * @route PUT /api/posts/:slug
 * @access Private
 * @requires Authentication (post author only)
 */
router.put('/:slug', protect, async (req, res) => {
  try {
    const post = await Post.findOne({ slug: req.params.slug });

    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Check if user is the author
    if (post.author.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to update this post' });
    }

    const { title, content, tags } = req.body;

    // Update fields if provided
    if (title) post.title = title;
    if (content) post.content = content;
    if (tags) post.tags = tags;

    // Slug will be auto-regenerated if title changed (via pre-save hook)
    const updatedPost = await post.save();
    res.json(updatedPost);
  } catch (err) {
    console.error('[updatePost]', err);
    res.status(400).json({ message: err.message || 'Failed to update post' });
  }
});

/**
 * Delete a post by slug
 * @route DELETE /api/posts/:slug
 * @access Private
 * @requires Authentication (post author only)
 */
router.delete('/:slug', protect, async (req, res) => {
  try {
    const post = await Post.findOne({ slug: req.params.slug });

    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Check if user is the author
    if (post.author.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to delete this post' });
    }

    await post.deleteOne();
    res.json({ message: 'Post deleted successfully' });
  } catch (err) {
    console.error('[deletePost]', err);
    res.status(500).json({ message: err.message || 'Failed to delete post' });
  }
});

export default router;
